# Generated by Django 4.2.4 on 2023-08-10 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_ticket_user_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='internalupdate',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='userupdate',
        ),
        migrations.AddField(
            model_name='ticket',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
