# Generated by Django 4.2.4 on 2023-09-02 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_remove_ticket_internalupdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='responders',
            field=models.ManyToManyField(blank=True, related_name='responders', to=settings.AUTH_USER_MODEL),
        ),
    ]
